# Form implementation generated from reading ui file 'd:\Coding\BlbniCheck\resources\ui\task_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TaskDialog(object):
    def setupUi(self, TaskDialog):
        TaskDialog.setObjectName("TaskDialog")
        TaskDialog.resize(322, 163)
        TaskDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        TaskDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(TaskDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelDescription = QtWidgets.QLabel(TaskDialog)
        self.labelDescription.setObjectName("labelDescription")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDescription)
        self.lineEditDescription = QtWidgets.QLineEdit(TaskDialog)
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditDescription)
        self.labelNotes = QtWidgets.QLabel(TaskDialog)
        self.labelNotes.setObjectName("labelNotes")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelNotes)
        self.labelDueDate = QtWidgets.QLabel(TaskDialog)
        self.labelDueDate.setObjectName("labelDueDate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDueDate)
        self.plainTextEditNotes = QtWidgets.QPlainTextEdit(TaskDialog)
        self.plainTextEditNotes.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEditNotes.setTabChangesFocus(True)
        self.plainTextEditNotes.setObjectName("plainTextEditNotes")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainTextEditNotes)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(TaskDialog)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.dateTimeEditDueDate = QtWidgets.QDateTimeEdit(TaskDialog)
        self.dateTimeEditDueDate.setMinimumDate(QtCore.QDate(1999, 12, 31))
        self.dateTimeEditDueDate.setCalendarPopup(True)
        self.dateTimeEditDueDate.setObjectName("dateTimeEditDueDate")
        self.horizontalLayout.addWidget(self.dateTimeEditDueDate)
        self.horizontalLayout.setStretch(1, 1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(TaskDialog)
        QtCore.QMetaObject.connectSlotsByName(TaskDialog)
        TaskDialog.setTabOrder(self.lineEditDescription, self.plainTextEditNotes)

    def retranslateUi(self, TaskDialog):
        _translate = QtCore.QCoreApplication.translate
        TaskDialog.setWindowTitle(_translate("TaskDialog", "Create a new Task"))
        self.labelDescription.setText(_translate("TaskDialog", "Description"))
        self.lineEditDescription.setPlaceholderText(_translate("TaskDialog", "Enter the Task title"))
        self.labelNotes.setText(_translate("TaskDialog", "Notes"))
        self.labelDueDate.setText(_translate("TaskDialog", "Due Date"))
        self.plainTextEditNotes.setPlaceholderText(_translate("TaskDialog", "Enter optional details (to be shown in Task tooltip)"))
        self.checkBox.setToolTip(_translate("TaskDialog", "Do not check if the Task has no Due Date."))
